---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
    attributes: {
      locking_resource: {
        restart_lock_acquire: {
          timeout: 3
        }
      }
    }
suites:
  - name: simple_locking_resource
    run_list:
      - 'recipe[locking_resource_test::simple_serialized_lock]'
  - name: held_serialized_lock
    run_list:
      - 'recipe[locking_resource_test::held_serialized_lock]'
  - name: exception_serialized_lock
    run_list:
      - 'recipe[locking_resource_test::exception_serialized_lock]'
  - name: serialized_process
    run_list:
      - 'recipe[locking_resource_test::serialized_process_lock_handling]'
  - name: re_run_lock_older
    run_list:
      - 'recipe[locking_resource_test::re_run_lock_older]'
  - name: re_run_lock_newer
    run_list:
      - 'recipe[locking_resource_test::re_run_lock_newer]'
