---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
    attributes: {
    }
suites:
  - name: simple_locking_resource
    run_list:
      - 'recipe[locking_resource_test::simple_serialized_lock]'
  - name: simple_colliding_lock_resource
    run_list:
      - 'recipe[locking_resource_test::held_serialized_lock]'
