---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
    attributes: {
    }
suites:
  - name: locking_resource
    run_list:
      - 'recipe[locking_resource_test::default]'
